### PR TITLE
RTL

### PR DESCRIPTION
**Pull request by Youhan**
Hi @RyanThompson 

I just finished the initial version of the RTL. 

For the Bootstrap, I have added `bootstrap.rtl.css` file into the `resources/css/bootstrap-rtl` directory and added that file to styles.css in the `metadata` partial view. Hope that's fine for now.

### CODE REVIEW

**Comment by Youhan** [comment]
:fire:
Please wait I have some more to commit to this branch.

**Comment by Youhan** [comment]
I am going to get rid of the `bootstrap.rtl.css` file and write a proper SCSS for it to be able to use the `_variables.scss` of the accelerant theme which is customizing the Bootstrap build. This will take some days to complete.

**Comment by RyanThompson** [comment]
Fantastic - thank you!

**Comment by RyanThompson** [comment]
Ill try and remove pull-left and pull-right stuff to help alleviate the need for this stuff.

**Comment by Youhan** [comment]
This is not finished yet.

**Pull request merged**
