### PR TITLE
Let me opt out of fixed table headers.

### PR DESCRIPTION
**Pull request by bloveless**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Why cause?

**Comment by RyanThompson** [comment]
I'm thinking of removing it tbh cause it's an aggressive change..

**Comment by bloveless** [comment]
It doesn't work when there are multiple tables on the same page. Just stacks them all on top of each other and makes every table impossible to use.

**Comment by RyanThompson** [comment]
Temporarily removed cause it breaks mobiles. Ill keep this open though as a reminder if it is fixed / brought back.

Did you like it otherwise?

**Pull request closed without merging**
