### PR TITLE
Bugfix: Link issue

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RyanThompson** [comment]
That's what blur does - when the the focus leaves the input. So I _don't_ think this is necessary.

**Comment by RyanThompson** [comment]
Correct me if I am wrong.

**Comment by Piterden** [comment]
I have focused search input just after form page in CP loaded. So it covers quarter of screen.

**Comment by RyanThompson** [comment]
Can you show me? Clicking outside of it should close it as well as escape.

**Comment by Piterden** [comment]
[bug-search.mp4.zip](https://github.com/pyrocms/accelerant-theme/files/1074650/bug-search.mp4.zip)

**Comment by RyanThompson** [comment]
Are you using tab or what? Looks like it’s pulling focus OUT of the page input? But there is no JS to do that.. JS to focus on first .form > input:visible then the search js is all separate but I don’t know / get how it’s pulling focus INTO search unless you’re triggering it somehow.

**Pull request closed without merging**
